#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobResume.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCity(City instance);
    partial void UpdateCity(City instance);
    partial void DeleteCity(City instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertCountary(Countary instance);
    partial void UpdateCountary(Countary instance);
    partial void DeleteCountary(Countary instance);
    partial void InsertDegree(Degree instance);
    partial void UpdateDegree(Degree instance);
    partial void DeleteDegree(Degree instance);
    partial void InsertInstitute(Institute instance);
    partial void UpdateInstitute(Institute instance);
    partial void DeleteInstitute(Institute instance);
    partial void InsertJobResumeBasic(JobResumeBasic instance);
    partial void UpdateJobResumeBasic(JobResumeBasic instance);
    partial void DeleteJobResumeBasic(JobResumeBasic instance);
    partial void InsertJobResumeExp(JobResumeExp instance);
    partial void UpdateJobResumeExp(JobResumeExp instance);
    partial void DeleteJobResumeExp(JobResumeExp instance);
    partial void InsertPreviousHistory(PreviousHistory instance);
    partial void UpdatePreviousHistory(PreviousHistory instance);
    partial void DeletePreviousHistory(PreviousHistory instance);
    partial void InsertJobResumeExtra(JobResumeExtra instance);
    partial void UpdateJobResumeExtra(JobResumeExtra instance);
    partial void DeleteJobResumeExtra(JobResumeExtra instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<City> Cities
		{
			get
			{
				return this.GetTable<City>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Countary> Countaries
		{
			get
			{
				return this.GetTable<Countary>();
			}
		}
		
		public System.Data.Linq.Table<Degree> Degrees
		{
			get
			{
				return this.GetTable<Degree>();
			}
		}
		
		public System.Data.Linq.Table<Institute> Institutes
		{
			get
			{
				return this.GetTable<Institute>();
			}
		}
		
		public System.Data.Linq.Table<JobResumeBasic> JobResumeBasics
		{
			get
			{
				return this.GetTable<JobResumeBasic>();
			}
		}
		
		public System.Data.Linq.Table<JobResumeExp> JobResumeExps
		{
			get
			{
				return this.GetTable<JobResumeExp>();
			}
		}
		
		public System.Data.Linq.Table<PreviousHistory> PreviousHistories
		{
			get
			{
				return this.GetTable<PreviousHistory>();
			}
		}
		
		public System.Data.Linq.Table<JobResumeExtra> JobResumeExtras
		{
			get
			{
				return this.GetTable<JobResumeExtra>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cities")]
	public partial class City : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private EntitySet<JobResumeBasic> _JobResumeBasics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public City()
		{
			this._JobResumeBasics = new EntitySet<JobResumeBasic>(new Action<JobResumeBasic>(this.attach_JobResumeBasics), new Action<JobResumeBasic>(this.detach_JobResumeBasics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="City_JobResumeBasic", Storage="_JobResumeBasics", ThisKey="Id", OtherKey="city")]
		public EntitySet<JobResumeBasic> JobResumeBasics
		{
			get
			{
				return this._JobResumeBasics;
			}
			set
			{
				this._JobResumeBasics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_JobResumeBasics(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.City1 = this;
		}
		
		private void detach_JobResumeBasics(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.City1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _fname;
		
		private string _lname;
		
		private string _email;
		
		private EntitySet<JobResumeBasic> _JobResumeBasics;
		
		private EntitySet<JobResumeExp> _JobResumeExps;
		
		private EntitySet<PreviousHistory> _PreviousHistories;
		
		private EntitySet<JobResumeExtra> _JobResumeExtras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public User()
		{
			this._JobResumeBasics = new EntitySet<JobResumeBasic>(new Action<JobResumeBasic>(this.attach_JobResumeBasics), new Action<JobResumeBasic>(this.detach_JobResumeBasics));
			this._JobResumeExps = new EntitySet<JobResumeExp>(new Action<JobResumeExp>(this.attach_JobResumeExps), new Action<JobResumeExp>(this.detach_JobResumeExps));
			this._PreviousHistories = new EntitySet<PreviousHistory>(new Action<PreviousHistory>(this.attach_PreviousHistories), new Action<PreviousHistory>(this.detach_PreviousHistories));
			this._JobResumeExtras = new EntitySet<JobResumeExtra>(new Action<JobResumeExtra>(this.attach_JobResumeExtras), new Action<JobResumeExtra>(this.detach_JobResumeExtras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fname
		{
			get
			{
				return this._fname;
			}
			set
			{
				if ((this._fname != value))
				{
					this.OnfnameChanging(value);
					this.SendPropertyChanging();
					this._fname = value;
					this.SendPropertyChanged("fname");
					this.OnfnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lname
		{
			get
			{
				return this._lname;
			}
			set
			{
				if ((this._lname != value))
				{
					this.OnlnameChanging(value);
					this.SendPropertyChanging();
					this._lname = value;
					this.SendPropertyChanged("lname");
					this.OnlnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_JobResumeBasic", Storage="_JobResumeBasics", ThisKey="Id", OtherKey="userId")]
		public EntitySet<JobResumeBasic> JobResumeBasics
		{
			get
			{
				return this._JobResumeBasics;
			}
			set
			{
				this._JobResumeBasics.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_JobResumeExp", Storage="_JobResumeExps", ThisKey="Id", OtherKey="userId")]
		public EntitySet<JobResumeExp> JobResumeExps
		{
			get
			{
				return this._JobResumeExps;
			}
			set
			{
				this._JobResumeExps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_PreviousHistory", Storage="_PreviousHistories", ThisKey="Id", OtherKey="userid")]
		public EntitySet<PreviousHistory> PreviousHistories
		{
			get
			{
				return this._PreviousHistories;
			}
			set
			{
				this._PreviousHistories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_JobResumeExtra", Storage="_JobResumeExtras", ThisKey="Id", OtherKey="userId")]
		public EntitySet<JobResumeExtra> JobResumeExtras
		{
			get
			{
				return this._JobResumeExtras;
			}
			set
			{
				this._JobResumeExtras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_JobResumeBasics(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_JobResumeBasics(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_JobResumeExps(JobResumeExp entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_JobResumeExps(JobResumeExp entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_PreviousHistories(PreviousHistory entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_PreviousHistories(PreviousHistory entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_JobResumeExtras(JobResumeExtra entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_JobResumeExtras(JobResumeExtra entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Countaries")]
	public partial class Countary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private EntitySet<JobResumeBasic> _JobResumeBasics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Countary()
		{
			this._JobResumeBasics = new EntitySet<JobResumeBasic>(new Action<JobResumeBasic>(this.attach_JobResumeBasics), new Action<JobResumeBasic>(this.detach_JobResumeBasics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Countary_JobResumeBasic", Storage="_JobResumeBasics", ThisKey="Id", OtherKey="country")]
		public EntitySet<JobResumeBasic> JobResumeBasics
		{
			get
			{
				return this._JobResumeBasics;
			}
			set
			{
				this._JobResumeBasics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_JobResumeBasics(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.Countary = this;
		}
		
		private void detach_JobResumeBasics(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.Countary = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Degree")]
	public partial class Degree : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private EntitySet<JobResumeBasic> _JobResumeBasics;
		
		private EntitySet<JobResumeBasic> _JobResumeBasics1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Degree()
		{
			this._JobResumeBasics = new EntitySet<JobResumeBasic>(new Action<JobResumeBasic>(this.attach_JobResumeBasics), new Action<JobResumeBasic>(this.detach_JobResumeBasics));
			this._JobResumeBasics1 = new EntitySet<JobResumeBasic>(new Action<JobResumeBasic>(this.attach_JobResumeBasics1), new Action<JobResumeBasic>(this.detach_JobResumeBasics1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Degree_JobResumeBasic", Storage="_JobResumeBasics", ThisKey="Id", OtherKey="lastdegree")]
		public EntitySet<JobResumeBasic> JobResumeBasics
		{
			get
			{
				return this._JobResumeBasics;
			}
			set
			{
				this._JobResumeBasics.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Degree_JobResumeBasic1", Storage="_JobResumeBasics1", ThisKey="Id", OtherKey="scndlastdegree")]
		public EntitySet<JobResumeBasic> JobResumeBasics1
		{
			get
			{
				return this._JobResumeBasics1;
			}
			set
			{
				this._JobResumeBasics1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_JobResumeBasics(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.Degree = this;
		}
		
		private void detach_JobResumeBasics(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.Degree = null;
		}
		
		private void attach_JobResumeBasics1(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.Degree1 = this;
		}
		
		private void detach_JobResumeBasics1(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.Degree1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Institutes")]
	public partial class Institute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private EntitySet<JobResumeBasic> _JobResumeBasics;
		
		private EntitySet<JobResumeBasic> _JobResumeBasics1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Institute()
		{
			this._JobResumeBasics = new EntitySet<JobResumeBasic>(new Action<JobResumeBasic>(this.attach_JobResumeBasics), new Action<JobResumeBasic>(this.detach_JobResumeBasics));
			this._JobResumeBasics1 = new EntitySet<JobResumeBasic>(new Action<JobResumeBasic>(this.attach_JobResumeBasics1), new Action<JobResumeBasic>(this.detach_JobResumeBasics1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Institute_JobResumeBasic", Storage="_JobResumeBasics", ThisKey="Id", OtherKey="lastinstitute")]
		public EntitySet<JobResumeBasic> JobResumeBasics
		{
			get
			{
				return this._JobResumeBasics;
			}
			set
			{
				this._JobResumeBasics.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Institute_JobResumeBasic1", Storage="_JobResumeBasics1", ThisKey="Id", OtherKey="scndlastinstitute")]
		public EntitySet<JobResumeBasic> JobResumeBasics1
		{
			get
			{
				return this._JobResumeBasics1;
			}
			set
			{
				this._JobResumeBasics1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_JobResumeBasics(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.Institute = this;
		}
		
		private void detach_JobResumeBasics(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.Institute = null;
		}
		
		private void attach_JobResumeBasics1(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.Institute1 = this;
		}
		
		private void detach_JobResumeBasics1(JobResumeBasic entity)
		{
			this.SendPropertyChanging();
			entity.Institute1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobResumeBasic")]
	public partial class JobResumeBasic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _mname;
		
		private string _image;
		
		private System.DateTime _dob;
		
		private string _gender;
		
		private string _ph1;
		
		private string _ph2;
		
		private string _address;
		
		private int _city;
		
		private int _country;
		
		private string _objective;
		
		private string _depofint;
		
		private string _desofint;
		
		private System.DateTime _joiningdate;
		
		private int _lastdegree;
		
		private int _lastinstitute;
		
		private string _perflastdegree;
		
		private int _scndlastdegree;
		
		private int _scndlastinstitute;
		
		private string _perfscndlastdegree;
		
		private string _addqualification;
		
		private int _userId;
		
		private EntityRef<City> _City1;
		
		private EntityRef<Countary> _Countary;
		
		private EntityRef<Degree> _Degree;
		
		private EntityRef<Institute> _Institute;
		
		private EntityRef<Degree> _Degree1;
		
		private EntityRef<Institute> _Institute1;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnmnameChanging(string value);
    partial void OnmnameChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OndobChanging(System.DateTime value);
    partial void OndobChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void Onph1Changing(string value);
    partial void Onph1Changed();
    partial void Onph2Changing(string value);
    partial void Onph2Changed();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(int value);
    partial void OncityChanged();
    partial void OncountryChanging(int value);
    partial void OncountryChanged();
    partial void OnobjectiveChanging(string value);
    partial void OnobjectiveChanged();
    partial void OndepofintChanging(string value);
    partial void OndepofintChanged();
    partial void OndesofintChanging(string value);
    partial void OndesofintChanged();
    partial void OnjoiningdateChanging(System.DateTime value);
    partial void OnjoiningdateChanged();
    partial void OnlastdegreeChanging(int value);
    partial void OnlastdegreeChanged();
    partial void OnlastinstituteChanging(int value);
    partial void OnlastinstituteChanged();
    partial void OnperflastdegreeChanging(string value);
    partial void OnperflastdegreeChanged();
    partial void OnscndlastdegreeChanging(int value);
    partial void OnscndlastdegreeChanged();
    partial void OnscndlastinstituteChanging(int value);
    partial void OnscndlastinstituteChanged();
    partial void OnperfscndlastdegreeChanging(string value);
    partial void OnperfscndlastdegreeChanged();
    partial void OnaddqualificationChanging(string value);
    partial void OnaddqualificationChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public JobResumeBasic()
		{
			this._City1 = default(EntityRef<City>);
			this._Countary = default(EntityRef<Countary>);
			this._Degree = default(EntityRef<Degree>);
			this._Institute = default(EntityRef<Institute>);
			this._Degree1 = default(EntityRef<Degree>);
			this._Institute1 = default(EntityRef<Institute>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mname", DbType="VarChar(50)")]
		public string mname
		{
			get
			{
				return this._mname;
			}
			set
			{
				if ((this._mname != value))
				{
					this.OnmnameChanging(value);
					this.SendPropertyChanging();
					this._mname = value;
					this.SendPropertyChanged("mname");
					this.OnmnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(50)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="Date NOT NULL")]
		public System.DateTime dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ph1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ph1
		{
			get
			{
				return this._ph1;
			}
			set
			{
				if ((this._ph1 != value))
				{
					this.Onph1Changing(value);
					this.SendPropertyChanging();
					this._ph1 = value;
					this.SendPropertyChanged("ph1");
					this.Onph1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ph2", DbType="VarChar(50)")]
		public string ph2
		{
			get
			{
				return this._ph2;
			}
			set
			{
				if ((this._ph2 != value))
				{
					this.Onph2Changing(value);
					this.SendPropertyChanging();
					this._ph2 = value;
					this.SendPropertyChanged("ph2");
					this.Onph2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="Int NOT NULL")]
		public int city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					if (this._City1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="Int NOT NULL")]
		public int country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					if (this._Countary.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objective", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string objective
		{
			get
			{
				return this._objective;
			}
			set
			{
				if ((this._objective != value))
				{
					this.OnobjectiveChanging(value);
					this.SendPropertyChanging();
					this._objective = value;
					this.SendPropertyChanged("objective");
					this.OnobjectiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depofint", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string depofint
		{
			get
			{
				return this._depofint;
			}
			set
			{
				if ((this._depofint != value))
				{
					this.OndepofintChanging(value);
					this.SendPropertyChanging();
					this._depofint = value;
					this.SendPropertyChanged("depofint");
					this.OndepofintChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desofint", DbType="VarChar(50)")]
		public string desofint
		{
			get
			{
				return this._desofint;
			}
			set
			{
				if ((this._desofint != value))
				{
					this.OndesofintChanging(value);
					this.SendPropertyChanging();
					this._desofint = value;
					this.SendPropertyChanged("desofint");
					this.OndesofintChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_joiningdate", DbType="Date NOT NULL")]
		public System.DateTime joiningdate
		{
			get
			{
				return this._joiningdate;
			}
			set
			{
				if ((this._joiningdate != value))
				{
					this.OnjoiningdateChanging(value);
					this.SendPropertyChanging();
					this._joiningdate = value;
					this.SendPropertyChanged("joiningdate");
					this.OnjoiningdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastdegree", DbType="Int NOT NULL")]
		public int lastdegree
		{
			get
			{
				return this._lastdegree;
			}
			set
			{
				if ((this._lastdegree != value))
				{
					if (this._Degree.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlastdegreeChanging(value);
					this.SendPropertyChanging();
					this._lastdegree = value;
					this.SendPropertyChanged("lastdegree");
					this.OnlastdegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastinstitute", DbType="Int NOT NULL")]
		public int lastinstitute
		{
			get
			{
				return this._lastinstitute;
			}
			set
			{
				if ((this._lastinstitute != value))
				{
					if (this._Institute.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlastinstituteChanging(value);
					this.SendPropertyChanging();
					this._lastinstitute = value;
					this.SendPropertyChanged("lastinstitute");
					this.OnlastinstituteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perflastdegree", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string perflastdegree
		{
			get
			{
				return this._perflastdegree;
			}
			set
			{
				if ((this._perflastdegree != value))
				{
					this.OnperflastdegreeChanging(value);
					this.SendPropertyChanging();
					this._perflastdegree = value;
					this.SendPropertyChanged("perflastdegree");
					this.OnperflastdegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scndlastdegree", DbType="Int NOT NULL")]
		public int scndlastdegree
		{
			get
			{
				return this._scndlastdegree;
			}
			set
			{
				if ((this._scndlastdegree != value))
				{
					if (this._Degree1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnscndlastdegreeChanging(value);
					this.SendPropertyChanging();
					this._scndlastdegree = value;
					this.SendPropertyChanged("scndlastdegree");
					this.OnscndlastdegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scndlastinstitute", DbType="Int NOT NULL")]
		public int scndlastinstitute
		{
			get
			{
				return this._scndlastinstitute;
			}
			set
			{
				if ((this._scndlastinstitute != value))
				{
					if (this._Institute1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnscndlastinstituteChanging(value);
					this.SendPropertyChanging();
					this._scndlastinstitute = value;
					this.SendPropertyChanged("scndlastinstitute");
					this.OnscndlastinstituteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfscndlastdegree", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string perfscndlastdegree
		{
			get
			{
				return this._perfscndlastdegree;
			}
			set
			{
				if ((this._perfscndlastdegree != value))
				{
					this.OnperfscndlastdegreeChanging(value);
					this.SendPropertyChanging();
					this._perfscndlastdegree = value;
					this.SendPropertyChanged("perfscndlastdegree");
					this.OnperfscndlastdegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addqualification", DbType="VarChar(50)")]
		public string addqualification
		{
			get
			{
				return this._addqualification;
			}
			set
			{
				if ((this._addqualification != value))
				{
					this.OnaddqualificationChanging(value);
					this.SendPropertyChanging();
					this._addqualification = value;
					this.SendPropertyChanged("addqualification");
					this.OnaddqualificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="City_JobResumeBasic", Storage="_City1", ThisKey="city", OtherKey="Id", IsForeignKey=true)]
		public City City1
		{
			get
			{
				return this._City1.Entity;
			}
			set
			{
				City previousValue = this._City1.Entity;
				if (((previousValue != value) 
							|| (this._City1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._City1.Entity = null;
						previousValue.JobResumeBasics.Remove(this);
					}
					this._City1.Entity = value;
					if ((value != null))
					{
						value.JobResumeBasics.Add(this);
						this._city = value.Id;
					}
					else
					{
						this._city = default(int);
					}
					this.SendPropertyChanged("City1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Countary_JobResumeBasic", Storage="_Countary", ThisKey="country", OtherKey="Id", IsForeignKey=true)]
		public Countary Countary
		{
			get
			{
				return this._Countary.Entity;
			}
			set
			{
				Countary previousValue = this._Countary.Entity;
				if (((previousValue != value) 
							|| (this._Countary.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Countary.Entity = null;
						previousValue.JobResumeBasics.Remove(this);
					}
					this._Countary.Entity = value;
					if ((value != null))
					{
						value.JobResumeBasics.Add(this);
						this._country = value.Id;
					}
					else
					{
						this._country = default(int);
					}
					this.SendPropertyChanged("Countary");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Degree_JobResumeBasic", Storage="_Degree", ThisKey="lastdegree", OtherKey="Id", IsForeignKey=true)]
		public Degree Degree
		{
			get
			{
				return this._Degree.Entity;
			}
			set
			{
				Degree previousValue = this._Degree.Entity;
				if (((previousValue != value) 
							|| (this._Degree.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Degree.Entity = null;
						previousValue.JobResumeBasics.Remove(this);
					}
					this._Degree.Entity = value;
					if ((value != null))
					{
						value.JobResumeBasics.Add(this);
						this._lastdegree = value.Id;
					}
					else
					{
						this._lastdegree = default(int);
					}
					this.SendPropertyChanged("Degree");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Institute_JobResumeBasic", Storage="_Institute", ThisKey="lastinstitute", OtherKey="Id", IsForeignKey=true)]
		public Institute Institute
		{
			get
			{
				return this._Institute.Entity;
			}
			set
			{
				Institute previousValue = this._Institute.Entity;
				if (((previousValue != value) 
							|| (this._Institute.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Institute.Entity = null;
						previousValue.JobResumeBasics.Remove(this);
					}
					this._Institute.Entity = value;
					if ((value != null))
					{
						value.JobResumeBasics.Add(this);
						this._lastinstitute = value.Id;
					}
					else
					{
						this._lastinstitute = default(int);
					}
					this.SendPropertyChanged("Institute");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Degree_JobResumeBasic1", Storage="_Degree1", ThisKey="scndlastdegree", OtherKey="Id", IsForeignKey=true)]
		public Degree Degree1
		{
			get
			{
				return this._Degree1.Entity;
			}
			set
			{
				Degree previousValue = this._Degree1.Entity;
				if (((previousValue != value) 
							|| (this._Degree1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Degree1.Entity = null;
						previousValue.JobResumeBasics1.Remove(this);
					}
					this._Degree1.Entity = value;
					if ((value != null))
					{
						value.JobResumeBasics1.Add(this);
						this._scndlastdegree = value.Id;
					}
					else
					{
						this._scndlastdegree = default(int);
					}
					this.SendPropertyChanged("Degree1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Institute_JobResumeBasic1", Storage="_Institute1", ThisKey="scndlastinstitute", OtherKey="Id", IsForeignKey=true)]
		public Institute Institute1
		{
			get
			{
				return this._Institute1.Entity;
			}
			set
			{
				Institute previousValue = this._Institute1.Entity;
				if (((previousValue != value) 
							|| (this._Institute1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Institute1.Entity = null;
						previousValue.JobResumeBasics1.Remove(this);
					}
					this._Institute1.Entity = value;
					if ((value != null))
					{
						value.JobResumeBasics1.Add(this);
						this._scndlastinstitute = value.Id;
					}
					else
					{
						this._scndlastinstitute = default(int);
					}
					this.SendPropertyChanged("Institute1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_JobResumeBasic", Storage="_User", ThisKey="userId", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.JobResumeBasics.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.JobResumeBasics.Add(this);
						this._userId = value.Id;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobResumeExp")]
	public partial class JobResumeExp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _skills;
		
		private int _minsalary;
		
		private string _expsummary;
		
		private string _expyrs;
		
		private string _cemployer;
		
		private string _cdes;
		
		private string _expcorg;
		
		private string _rescjob;
		
		private int _userId;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnskillsChanging(string value);
    partial void OnskillsChanged();
    partial void OnminsalaryChanging(int value);
    partial void OnminsalaryChanged();
    partial void OnexpsummaryChanging(string value);
    partial void OnexpsummaryChanged();
    partial void OnexpyrsChanging(string value);
    partial void OnexpyrsChanged();
    partial void OncemployerChanging(string value);
    partial void OncemployerChanged();
    partial void OncdesChanging(string value);
    partial void OncdesChanged();
    partial void OnexpcorgChanging(string value);
    partial void OnexpcorgChanged();
    partial void OnrescjobChanging(string value);
    partial void OnrescjobChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public JobResumeExp()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skills", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string skills
		{
			get
			{
				return this._skills;
			}
			set
			{
				if ((this._skills != value))
				{
					this.OnskillsChanging(value);
					this.SendPropertyChanging();
					this._skills = value;
					this.SendPropertyChanged("skills");
					this.OnskillsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minsalary", DbType="Int NOT NULL")]
		public int minsalary
		{
			get
			{
				return this._minsalary;
			}
			set
			{
				if ((this._minsalary != value))
				{
					this.OnminsalaryChanging(value);
					this.SendPropertyChanging();
					this._minsalary = value;
					this.SendPropertyChanged("minsalary");
					this.OnminsalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expsummary", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string expsummary
		{
			get
			{
				return this._expsummary;
			}
			set
			{
				if ((this._expsummary != value))
				{
					this.OnexpsummaryChanging(value);
					this.SendPropertyChanging();
					this._expsummary = value;
					this.SendPropertyChanged("expsummary");
					this.OnexpsummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expyrs", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string expyrs
		{
			get
			{
				return this._expyrs;
			}
			set
			{
				if ((this._expyrs != value))
				{
					this.OnexpyrsChanging(value);
					this.SendPropertyChanging();
					this._expyrs = value;
					this.SendPropertyChanged("expyrs");
					this.OnexpyrsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cemployer", DbType="VarChar(50)")]
		public string cemployer
		{
			get
			{
				return this._cemployer;
			}
			set
			{
				if ((this._cemployer != value))
				{
					this.OncemployerChanging(value);
					this.SendPropertyChanging();
					this._cemployer = value;
					this.SendPropertyChanged("cemployer");
					this.OncemployerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdes", DbType="NChar(10)")]
		public string cdes
		{
			get
			{
				return this._cdes;
			}
			set
			{
				if ((this._cdes != value))
				{
					this.OncdesChanging(value);
					this.SendPropertyChanging();
					this._cdes = value;
					this.SendPropertyChanged("cdes");
					this.OncdesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expcorg", DbType="VarChar(50)")]
		public string expcorg
		{
			get
			{
				return this._expcorg;
			}
			set
			{
				if ((this._expcorg != value))
				{
					this.OnexpcorgChanging(value);
					this.SendPropertyChanging();
					this._expcorg = value;
					this.SendPropertyChanged("expcorg");
					this.OnexpcorgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rescjob", DbType="VarChar(50)")]
		public string rescjob
		{
			get
			{
				return this._rescjob;
			}
			set
			{
				if ((this._rescjob != value))
				{
					this.OnrescjobChanging(value);
					this.SendPropertyChanging();
					this._rescjob = value;
					this.SendPropertyChanged("rescjob");
					this.OnrescjobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_JobResumeExp", Storage="_User", ThisKey="userId", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.JobResumeExps.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.JobResumeExps.Add(this);
						this._userId = value.Id;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PreviousHistory")]
	public partial class PreviousHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _pemployer;
		
		private string _pdes;
		
		private string _expporg;
		
		private string _resppjob;
		
		private System.Nullable<System.DateTime> _dateofleaving;
		
		private int _userid;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnpemployerChanging(string value);
    partial void OnpemployerChanged();
    partial void OnpdesChanging(string value);
    partial void OnpdesChanged();
    partial void OnexpporgChanging(string value);
    partial void OnexpporgChanged();
    partial void OnresppjobChanging(string value);
    partial void OnresppjobChanged();
    partial void OndateofleavingChanging(System.Nullable<System.DateTime> value);
    partial void OndateofleavingChanged();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    #endregion
		
		public PreviousHistory()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pemployer", DbType="VarChar(50)")]
		public string pemployer
		{
			get
			{
				return this._pemployer;
			}
			set
			{
				if ((this._pemployer != value))
				{
					this.OnpemployerChanging(value);
					this.SendPropertyChanging();
					this._pemployer = value;
					this.SendPropertyChanged("pemployer");
					this.OnpemployerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdes", DbType="VarChar(50)")]
		public string pdes
		{
			get
			{
				return this._pdes;
			}
			set
			{
				if ((this._pdes != value))
				{
					this.OnpdesChanging(value);
					this.SendPropertyChanging();
					this._pdes = value;
					this.SendPropertyChanged("pdes");
					this.OnpdesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expporg", DbType="VarChar(50)")]
		public string expporg
		{
			get
			{
				return this._expporg;
			}
			set
			{
				if ((this._expporg != value))
				{
					this.OnexpporgChanging(value);
					this.SendPropertyChanging();
					this._expporg = value;
					this.SendPropertyChanged("expporg");
					this.OnexpporgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resppjob", DbType="VarChar(50)")]
		public string resppjob
		{
			get
			{
				return this._resppjob;
			}
			set
			{
				if ((this._resppjob != value))
				{
					this.OnresppjobChanging(value);
					this.SendPropertyChanging();
					this._resppjob = value;
					this.SendPropertyChanged("resppjob");
					this.OnresppjobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateofleaving", DbType="Date")]
		public System.Nullable<System.DateTime> dateofleaving
		{
			get
			{
				return this._dateofleaving;
			}
			set
			{
				if ((this._dateofleaving != value))
				{
					this.OndateofleavingChanging(value);
					this.SendPropertyChanging();
					this._dateofleaving = value;
					this.SendPropertyChanged("dateofleaving");
					this.OndateofleavingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_PreviousHistory", Storage="_User", ThisKey="userid", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.PreviousHistories.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.PreviousHistories.Add(this);
						this._userid = value.Id;
					}
					else
					{
						this._userid = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobResumeExtra")]
	public partial class JobResumeExtra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _extraactivities;
		
		private string _otherinterests;
		
		private string _namep1;
		
		private string _affp1;
		
		private string _php1;
		
		private string _emailp1;
		
		private string _namep2;
		
		private string _affp2;
		
		private string _php2;
		
		private string _emailp2;
		
		private int _userId;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnextraactivitiesChanging(string value);
    partial void OnextraactivitiesChanged();
    partial void OnotherinterestsChanging(string value);
    partial void OnotherinterestsChanged();
    partial void Onnamep1Changing(string value);
    partial void Onnamep1Changed();
    partial void Onaffp1Changing(string value);
    partial void Onaffp1Changed();
    partial void Onphp1Changing(string value);
    partial void Onphp1Changed();
    partial void Onemailp1Changing(string value);
    partial void Onemailp1Changed();
    partial void Onnamep2Changing(string value);
    partial void Onnamep2Changed();
    partial void Onaffp2Changing(string value);
    partial void Onaffp2Changed();
    partial void Onphp2Changing(string value);
    partial void Onphp2Changed();
    partial void Onemailp2Changing(string value);
    partial void Onemailp2Changed();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public JobResumeExtra()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extraactivities", DbType="VarChar(50)")]
		public string extraactivities
		{
			get
			{
				return this._extraactivities;
			}
			set
			{
				if ((this._extraactivities != value))
				{
					this.OnextraactivitiesChanging(value);
					this.SendPropertyChanging();
					this._extraactivities = value;
					this.SendPropertyChanged("extraactivities");
					this.OnextraactivitiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherinterests", DbType="VarChar(50)")]
		public string otherinterests
		{
			get
			{
				return this._otherinterests;
			}
			set
			{
				if ((this._otherinterests != value))
				{
					this.OnotherinterestsChanging(value);
					this.SendPropertyChanging();
					this._otherinterests = value;
					this.SendPropertyChanged("otherinterests");
					this.OnotherinterestsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namep1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string namep1
		{
			get
			{
				return this._namep1;
			}
			set
			{
				if ((this._namep1 != value))
				{
					this.Onnamep1Changing(value);
					this.SendPropertyChanging();
					this._namep1 = value;
					this.SendPropertyChanged("namep1");
					this.Onnamep1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_affp1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string affp1
		{
			get
			{
				return this._affp1;
			}
			set
			{
				if ((this._affp1 != value))
				{
					this.Onaffp1Changing(value);
					this.SendPropertyChanging();
					this._affp1 = value;
					this.SendPropertyChanged("affp1");
					this.Onaffp1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_php1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string php1
		{
			get
			{
				return this._php1;
			}
			set
			{
				if ((this._php1 != value))
				{
					this.Onphp1Changing(value);
					this.SendPropertyChanging();
					this._php1 = value;
					this.SendPropertyChanged("php1");
					this.Onphp1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailp1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string emailp1
		{
			get
			{
				return this._emailp1;
			}
			set
			{
				if ((this._emailp1 != value))
				{
					this.Onemailp1Changing(value);
					this.SendPropertyChanging();
					this._emailp1 = value;
					this.SendPropertyChanged("emailp1");
					this.Onemailp1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namep2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string namep2
		{
			get
			{
				return this._namep2;
			}
			set
			{
				if ((this._namep2 != value))
				{
					this.Onnamep2Changing(value);
					this.SendPropertyChanging();
					this._namep2 = value;
					this.SendPropertyChanged("namep2");
					this.Onnamep2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_affp2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string affp2
		{
			get
			{
				return this._affp2;
			}
			set
			{
				if ((this._affp2 != value))
				{
					this.Onaffp2Changing(value);
					this.SendPropertyChanging();
					this._affp2 = value;
					this.SendPropertyChanged("affp2");
					this.Onaffp2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_php2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string php2
		{
			get
			{
				return this._php2;
			}
			set
			{
				if ((this._php2 != value))
				{
					this.Onphp2Changing(value);
					this.SendPropertyChanging();
					this._php2 = value;
					this.SendPropertyChanged("php2");
					this.Onphp2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailp2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string emailp2
		{
			get
			{
				return this._emailp2;
			}
			set
			{
				if ((this._emailp2 != value))
				{
					this.Onemailp2Changing(value);
					this.SendPropertyChanging();
					this._emailp2 = value;
					this.SendPropertyChanged("emailp2");
					this.Onemailp2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_JobResumeExtra", Storage="_User", ThisKey="userId", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.JobResumeExtras.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.JobResumeExtras.Add(this);
						this._userId = value.Id;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
